# Generated by Django 4.1 on 2022-08-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recdots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="create_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="create_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
