# Generated by Django 4.1 on 2022-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Behavior",
            fields=[
                ("index", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("item_id", models.IntegerField()),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
                ("behave_type", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.IntegerField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=255)),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Rec",
            fields=[
                ("index", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("item_ids", models.CharField(max_length=255)),
                ("clicked_ids", models.CharField(max_length=1024)),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255)),
                ("user_type", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
            ],
        ),
    ]
