# Generated by Django 4.1 on 2022-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_item_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rec",
            name="index",
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
