# Generated by Django 4.1 on 2022-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_alter_rec_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behavior",
            name="index",
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_id",
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
