# Generated by Django 4.1 on 2022-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0004_alter_behavior_index_alter_item_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behavior",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rec",
            name="clicked_ids",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
