# Generated by Django 4.1 on 2022-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_alter_behavior_score_alter_rec_clicked_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="clicked_time",
            field=models.IntegerField(default=0),
        ),
    ]
